MANDATORY_FIELDS = {
    "partner": str,
	"project_name": str,
	"solar_farm_type": str,
	"commission_date": str,
	"crediting_period_start_date": str,
	"crediting_period_end_date": str,
	"location_state": str,
	"location_district": str,
	"gps_latitude": float,
	"gps_longitude": float,
	"dc_installed_capacity_mwp": float,
	"ac_installed_capacity_mw": float,
}

OPTIONAL_FIELDS = [
	"applicable_methodology",
	"land_use_type_prior",
	"verra_gs_registry_project_id",
	"cea_registration_number",
	"discom_seb_registration_number",
	"grid_emission_factor",
	"emission_factor_reference_year",
	"panel_technology",
	"panel_wattage_wp",
	"total_number_of_panels",
	"inverter_type",
	"number_of_inverters",
	"design_performance_ratio",
	"design_capacity_utilization_factor",
	"grid_substation_name",
	"grid_connection_voltage_kv",
	"grid_connection_type",
	"offtaker_ppa_counterparty_name",
	"metering_point_location",
	"revenue_meter_serial_numbers",
	"revenue_meter_accuracy_class",
	"revenue_meter_ownership",
	"meter_calibration_certificate_date",
	"auxiliary_meter_serial_number",
]

ALLOWED_VALUES = {
	"solar_farm_type": ["Ground-Mounted", "Rooftop", "Floating", "Agrivoltaic"],
	"panel_technology": ["Mono-PERC", "Bifacial", "Polycrystalline", "TOPCon", "HJT"],
	"inverter_type": ["String", "Central", "Microinverter"],
	"grid_connection_type": ["Captive", "Open Access", "Net-Metering", "Third-Party Sale", "PPA"],
	"grid_connection_voltage_kv": ["11", "33", "66", "110", "220"],
	"metering_point_location": ["Grid Injection Point", "Plant Busbar"],
	"revenue_meter_accuracy_class": ["Class 0.2S", "Class 0.5S", "Class 1.0S"],
	"revenue_meter_ownership": ["Project Company", "DISCOM", "Third Party"],
	"land_use_type_prior": ["Wasteland", "Degraded Land", "Agricultural", "Forest"],
}
