MANDATORY_FIELDS = {
    "partner": str,
	"project_name": str,
	"bess_configuration": str,
	"commission_date": str,
	"crediting_period_start_date": str,
	"crediting_period_end_date": str,
	"location_state": str,
	"location_district": str,
	"gps_latitude": float,
	"gps_longitude": float,
	"battery_technology": str,
	"rated_energy_capacity_kwh": float,
	"rated_power_output_kw": float,
}

OPTIONAL_FIELDS = [
	"coupled_project_reference",
	"applicable_methodology",
	"bess_operating_mode",
	"verra_gs_registry_project_id",
	"cerc_cea_registration_number",
	"discom_interconnection_agreement_no",
	"grid_emission_factor",
	"emission_factor_reference_year",
	"battery_manufacturer",
	"battery_cell_model",
	"c_rate",
	"number_of_battery_racks",
	"design_round_trip_efficiency_pct",
	"design_depth_of_discharge_pct",
	"design_soh_at_end_of_life_pct",
	"battery_thermal_management_type",
	"pcs_rated_power_kw",
	"pcs_efficiency_pct",
	"number_of_pcs_units",
	"ac_connection_voltage_kv",
	"bms_manufacturer_model",
	"ems_scada_system",
	"data_logger_sampling_frequency_mins",
	"grid_substation_name",
	"grid_connection_voltage_kv",
	"revenue_meter_serial_number",
	"revenue_meter_accuracy_class",
	"revenue_meter_ownership",
	"revenue_meter_calibration_date",
]

ALLOWED_VALUES = {
	"bess_configuration": ["Coupled with Renewable", "Standalone Grid-Connected"],
	"bess_operating_mode": ["Peak Shaving", "Frequency Regulation", "Energy Arbitrage", "Renewable Firming", "Ancillary Services"],
	"battery_technology": ["LFP", "NMC", "NCA", "Na-ion", "Zinc-Bromide Flow", "Vanadium Flow"],
	"battery_thermal_management_type": ["Air Cooling", "Liquid Cooling", "Phase Change Material"],
	"grid_connection_voltage_kv": ["11", "33", "66"],
	"revenue_meter_accuracy_class": ["Class 0.2S", "Class 0.5S"],
	"revenue_meter_ownership": ["Project Company", "DISCOM", "Third Party"],
}
